server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/accountdb
    username: postgres
    password: root123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  application:
    name: Account
  profiles:
    active: prod
  config:
    import: "optional:configserver:http://localhost:8071/"



# actuator endpoint
management:
  endpoints:
    web:
      exposure:
        include: "*"






#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest



#  config:
#    import:
#      - "application-dev.yml"
#      - "application-prod.yml"
#  profiles:
#    active:
#      - prod

#build:
#  version: '1.0'
#
#accounts:
#  message: "Welcome to SBIBANK accounts related local APIs "
#  contactDetails:
#    name: "ATUL PATEL - QA Lead"
#    email: "atul@gmail.com.com"
#  onCallSupport:
#    - (555) 555-1234
#    - (555) 523-1345
#
#


