server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/accountdb
    username: postgres
    password: root123

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: Account
  profiles:
    active: prod
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true


# actuator endpoint
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:  # for eureka server
      enabled: true

  metrics:
    tags:
      application: ${spring.application.name}


  info:
    env:
      enabled: true


endpoints:
  shutdown:
    enabled: true



eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "Accounts"
    description: "SBI Bank Accounts Application"
    version: "1.0.0"


logging:
  level:
    com:
      banck:
        account: DEBUG




resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000

resilience4j:
  retry:
    instances:
      default:
        max-attempts: 3
        waitDuration: 500
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        #      ignoreExceptions:
        #        - java.lang.NullPointerException
        retryExceptions:
          - java.util.concurrent.TimeoutException
resilience4j.ratelimiter:
  configs:
    default:
      timeoutDuration: 1000
      limitRefreshPeriod: 5000
      limitForPeriod: 1






#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest



#  config:
#    import:
#      - "application-dev.yml"
#      - "application-prod.yml"
#  profiles:
#    active:
#      - prod

#build:
#  version: '1.0'
#
#accounts:
#  message: "Welcome to SBIBANK accounts related local APIs "
#  contactDetails:
#    name: "ATUL PATEL - QA Lead"
#    email: "atul@gmail.com.com"
#  onCallSupport:
#    - (555) 555-1234
#    - (555) 523-1345
#
#


