server:
  port: 8080

spring:
  datasource:
#    url: jdbc:postgresql://localhost:3308/account
    url: jdbc:postgresql://localhost:3307/Service_ProvideDB
    username: postgres
    password: root123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true





