server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:3308/account
#    url: jdbc:postgresql://localhost:3307/Service_ProvideDB
    username: postgres
    password: root123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  config:
    import:
      - "application-dev.yml"
      - "application-prod.yml"
  profiles:
    active:
      - prod

build:
  version: '1.0'

accounts:
  message: "Welcome to SBIBANK accounts related local APIs "
  contactDetails:
    name: "ATUL PATEL - QA Lead"
    email: "atul@gmail.com.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345




