server:
  port: 8071
spring:
  application:
    name: configserver

  profiles:
    active: git
  #    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/atul-patel-silver/Bank-System-Configration.git
          default-label: master
          timeout: 5
          clone-on-start: true  # try cloning of ht GitHub repo
          force-pull: true


#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

encrypt:
  key: 45D81EC1EF61DF9AD8D3E5BB397F9

management:
  endpoints:
    web:
      exposure:
        include: "*"

  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true

    info:
      env:
        enabled: true

  metrics:
    tags:
      application: ${spring.application.name}

endpoints:
  shutdown:
    enabled: true



info:
  app:
    name: "configserver"
    description: "SBI BANK Config Server"
    version: "1.0.0"


#        native:
#          search-locations: classpath:/config
#          search-locations: file:///C:/Users/baps/Desktop/new-microservices/microservice/Bank-System/file-system-config-approach