
server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:3308/account
#    url: jdbc:postgresql://localhost:3307/Service_ProvideDB
    username: postgres
    password: root123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  profiles:
    active: prod
  application:
    name: Cards
  config:
    import: "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
# actuator endpoint
management:
  endpoints:
    web:
      exposure:
        include: "*"





#  config:
#    import:
#      - "application-dev.yml"
#      - "application-prod.yml"
#build:
#  version: "3.0"
#
#cards:
#  message: "Welcome to SBIBank cards related local APIs "
#  contactDetails:
#    name: "ATUL PATEL - QA Lead"
#    email: "atul@gmail.com.com"
#  onCallSupport:
#    - (412) 419-3491
#    - (915) 382-1932
