

server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:3308/account
#    url: jdbc:postgresql://localhost:3307/Service_ProvideDB
    username: postgres
    password: root123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  config:
    import:
      - "application-dev.yml"
      - "application-prod.yml"
  profiles:
    active:
      - "dev"




build:
  version: "3.0"

cards:
  message: "Welcome to SBIBank cards related local APIs "
  contactDetails:
    name: "ATUL PATEL - QA Lead"
    email: "atul@gmail.com.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932
