spring:
  config:
    activate:
      on-profile: "dev"

build:
  version: "2.0"

cards:
  message: "Welcome to SBI cards related QA APIs "
  contactDetails:
    name: "ATUL PATEL - QA Lead"
    email: "atul@gmail.com.com"
  onCallSupport:
    - (310) 875-4367
    - (201) 236-1267