spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

loans:
  message: "Welcome to SBIBank loans related prod APIs "
  contactDetails:
    name: "ATUL PATEL - QA Lead"
    email: "atul@gmail.com.com"
  onCallSupport:
    - (723) 656-8709
    - (156) 342-0956