server:
  port: 8091

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/loandb
    username: postgres
    password: root123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  application:
    name: Loan
  config:
    import: "optional:configserver:http://localhost:8071/"

  profiles:
    active: prod





# actuator endpoint
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown: # for eureka server
      enabled: true
  info:
    env:
      enabled: true

  metrics:
    tags:
      application: ${spring.application.name}

endpoints:
  shutdown:
    enabled: true


eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "loans"
    description: "SBI BANK Loans Application"
    version: "1.0.0"

logging:
  level:
    com:
      bank:
        loan: DEBUG
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest



#  config:
#    import:
#      - "application-dev.yml"
#      - "application-prod.yml"
#build:
#  version: "3.0"
#
#loans:
#  message: "Welcome to SBIBank loans related local APIs "
#  contactDetails:
#    name: "ATUL PATEL - QA Lead"
#    email: "atul@gmail.com.com"
#  onCallSupport:
#    - (452) 456-2176
#    - (546) 764-8934
#
#
