
server:
  port: 8091

spring:
  datasource:
    url: jdbc:postgresql://localhost:3308/account
#    url: jdbc:postgresql://localhost:3307/Service_ProvideDB
    username: postgres
    password: root123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  application:
    name: Loan
  config:
    import: "optional:configserver:http://localhost:8071/"

  profiles:
    active: prod
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest



# actuator endpoint
management:
  endpoints:
    web:
      exposure:
        include: "*"






#  config:
#    import:
#      - "application-dev.yml"
#      - "application-prod.yml"
#build:
#  version: "3.0"
#
#loans:
#  message: "Welcome to SBIBank loans related local APIs "
#  contactDetails:
#    name: "ATUL PATEL - QA Lead"
#    email: "atul@gmail.com.com"
#  onCallSupport:
#    - (452) 456-2176
#    - (546) 764-8934
#
#
