
server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:3308/account
    username: postgres
    password: root123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


