spring:
  application:
    name: gatewayserver
  config:
    import: "optional:configserver:http://localhost:8071/"

    # find all the register microservice in eurka server url
  cloud:
    gateway:
      httpclient:
        # time out configration as yml file
        connect-timeout: 1000
        response-timeout: 5s
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

  # redis server configration for rate limiter
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s


#enable all actuator endpoint
management:
  endpoints:
    web:
      exposure:
        include: "*"
        # all routing related to microservice

# for all actuator property
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true


info:
  app:
    name: "gateway server"
    description: "SBI BANK gateway server"
    version: "1.0.0"


#
logging:
  level:
    com:
      gateway:
        sever: DEBUG


# Circute Breaker
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000

