services:
  configserver:
    image: "atulpatel2001/configserver:s4"
    container_name: "configserver_ms"
    ports:
      - "8071:8071"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - atulpatel2001

  accounts:
    image: "atulpatel2001/account:s4"
    container_name: "account_ms"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - atulpatel2001
    environment:
      SPRING_APPLICATION_NAME: "Account"
      SPRING_CONFIG_IMPORT: "configserver:http://localhost:8071/"
      SPRING_PROFILES_ACTIVE: default


  loan:
    image: "atulpatel2001/loan:s4"
    container_name: "loan_ms"
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - atulpatel2001

    environment:
      SPRING_APPLICATION_NAME: "Loan"
      SPRING_CONFIG_IMPORT: "configserver:http://localhost:8071/"
      SPRING_PROFILES_ACTIVE: default

  cards:
    image: "atulpatel2001/cards:s4"
    container_name: "cards_ms"
    ports:
      - "8091:8091"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - atulpatel2001
    environment:
      SPRING_APPLICATION_NAME: "Cards"
      SPRING_CONFIG_IMPORT: "configserver:http://localhost:8071/"
      SPRING_PROFILES_ACTIVE: default


networks:
  atulpatel2001:
    driver: "bridge"
